### ISSUE TITLE
Crashes on RISC OS PC emulators

### ISSUE THREAD

**Issue by LinuxJedi** [MobyGamer/TOPBENCH#5]
TOPBENCH will not run properly on either PCEm or FasterPC emulators on RISC OS. With PCEm the VM dies with an "Invalid Opcode" error, on FasterPC it does with a similar error when the benchmark is run.

I'm not quite sure how to debug this.

**Comment by MobyGamer** [comment]
I think it's safe to say the fault lies with the emulators, not TOPBENCH.
