### ISSUE TITLE
Clarify License

### ISSUE THREAD

**Issue by kevinferrare** [MobyGamer/TOPBENCH#7]
Hello,

I would like to use your project to do automatic performances tests of our emulator ( https://github.com/OpenRakis/Spice86 )
This implies that we would depend on it.
I cannot find a LICENSE file in the repo, is it OK to use it? Our licence is Apache 2.0

**Comment by MobyGamer** [comment]
I've gone ahead and MIT-licensed it for you, so you should be good to go.  Thanks for your interest, and good luck with your emulator!
